name: mobile_app
description: "A citizen reporting application for Piura." # Descripción mejorada
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Para formato de fecha/hora en español
    sdk: flutter

  # Iconos estándar
  cupertino_icons: ^1.0.8

  # Comunicación y Datos
  http: ^1.2.1
  shared_preferences: ^2.2.3
  socket_io_client: ^3.1.2 # Usado en socket_service.dart
  jwt_decoder: ^2.0.1      # Usado en auth_provider.dart

  # State Management
  provider: ^6.1.2

  # Geoespacial y Mapas
  flutter_map: ^8.0.0 # Chequea si esta versión mayor causa problemas
  latlong2: ^0.9.1
  geolocator: ^14.0.0 # Chequea si esta versión mayor causa problemas
  permission_handler: ^12.0.1 # Chequea si esta versión mayor causa problemas
  flutter_map_marker_cluster: ^8.0.0 # Debe coincidir con flutter_map

  # UI y Utilidades
  image_picker: ^1.1.2
  intl: ^0.20.2 # Necesario para formateo de fechas/horas
  shimmer: ^3.0.0 # Para los esqueletos de carga
  fl_chart: ^1.1.1 # Para gráficos

  # Funcionalidades Nativas y Archivos
  flutter_local_notifications: ^19.0.0 # Chequea si esta versión mayor causa problemas
  flutter_background_service: ^5.0.1
  pdf: ^3.11.3 # Para generar PDF
  path_provider: ^2.1.5 # Para encontrar rutas de archivos
  open_file: ^3.5.10 # Para abrir archivos generados (PDF)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0 # Mantenemos el linter

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/ # Asegúrate que esta carpeta exista y contenga las fuentes Roboto